### ISSUE TITLE
Alternative contact method

### ISSUE THREAD

**Issue by svalo** [Andrea055/Andrea055#1]
Hi! I wanted to contact you to ask a few questions about https://github.com/andreock/vmg8825_b50b (or the -I think- former [repo ](https://github.com/Andrea055/VMG8828-B50) )but the issues there are closed, is there any other way to contact you beside telegram?

**Comment by andreock** [comment]
Use email, vivanco11.ac@gmail.com

**Comment by svalo** [comment]
Thank you!
